### ISSUE TITLE
Latest hashicorp/packer:full points to an old version of packer

### ISSUE THREAD

**Issue by mikhailadvani** [hashicorp/docker-hub-images#64]
The hashicorp/packer:full contains an old dev version of packer instead of the latest

Actual Output:
```
$ docker run -it  hashicorp/packer:full version
Packer v1.2.3-dev

Your version of Packer is out of date! The latest version
is 1.3.1. You can update by downloading from www.packer.io/downloads.html
```

Expected Output:
```
$ docker run -it  hashicorp/packer:full version
Packer v1.3.1
```

**Comment by cameronbrunner** [comment]
Ran into this today after noticing the build was based on alpine 3.7.  It appears that this is a regression and was caused by a manual push to the repository outside of the automated builder.  The push was done 'a month ago' while the last valid 'full' build was 2 months ago and was based on 3.8...

https://hub.docker.com/r/hashicorp/packer/builds/bdr7b9q5kgrkwjrxn6ruosa/

**Comment by OlivierCazade** [comment]
Also ran into this today :

```
$ docker run -it  hashicorp/packer:full version
Packer v1.2.3-dev

Your version of Packer is out of date! The latest version
is 1.4.3. You can update by downloading from www.packer.io/downloads.html
```

**Comment by SwampDragons** [comment]
this has been fixed :)
