### ISSUE TITLE
Terraform Light Docker 0.6.16 Fails to run

### ISSUE THREAD

**Issue by mindw** [hashicorp/docker-hub-images#7]
```
$ docker run -ti hashicorp/terraform:light  version
docker: Error response from daemon: Container command '/bin/terraform' not found or does not exist..
```

The full version runs as expected:

```
$ docker run -ti hashicorp/terraform:0.6.16  version
Terraform v0.6.16
```

This is a regression with the linux binaries - v0.6.15 binaries have no issue.

**Comment by flyinprogrammer** [comment]
i agree this is broken.

**Comment by timfallmk** [comment]
@mindw @flyinprogrammer Sorry guys, this is a known issue and is happening all over the place. There were some changes in musl for alpine that seem to have broken dynamic go builds. We're changing our `gox` builds to build static for all platforms by default and this should be fixed soon.

**Comment by flyinprogrammer** [comment]
@timfallmk no worries buddy 😄

**Comment by timfallmk** [comment]
Just FYI, for anyone following along, the problem seems to be in `go build`. On some platforms `go` will default to dynamic builds, and static on others.  Which happens where, and for what reason, is unclear. As an additional wrinkle, using `cgo` (or similar libraries) can force a dynamic build. It would seem that the changes to `musl` and `go` make dynamic builds fail on platforms that use different C libs.

The permanent solution is to build everything statically, but we're moving over to that slowly.

Related bits here:
https://github.com/gliderlabs/docker-alpine/issues/78
https://github.com/golang/go/issues/12808

**Comment by clarkgaybel** [comment]
FYI I've been facing the same issue and downgraded to 0.6.15.
After some days with no problem, I'm facing the problem again.

![image](https://cloud.githubusercontent.com/assets/3235805/16309660/ef810e16-393f-11e6-930b-a3bec520809e.png)

**Comment by cornfeedhobo** [comment]
This makes me a sad panda

**Comment by leopoldodonnell** [comment]
As of Aug 2nd 2016 the 0.6.15 appears to work - at least for me. Looking forward to upgrading though ;)

**Comment by timfallmk** [comment]
I'm not working on this anymore so I don't know if the necessary changes were incorporated into hashicorp/terraform. In the meantime you can probably use `timfallmk/terraform:0.7.0`

**Comment by paultyng** [comment]
We no longer build Terraform docker images from this repository (Packer images are built here still).

Issues and pull requests on the Terraform docker image should be opened on the main Terraform repository: https://github.com/hashicorp/terraform
